name: ble_provisioner
description: "A bluetooth base wifi provisioning app."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_blue_plus: '>=1.32.9 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/ble_provisioner_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true\
  image_path: "assets/icons/ble_provisioner_icon.png"
  remove_alpha_ios: true